name: Release

on:
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint
      - run: npm test

  release:
    needs: lint-and-test
    runs-on: self-hosted
    env:
      VERSION: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Determine previous tag & commits
        id: prev
        run: |
          if git tag | grep . >/dev/null; then
            PREV_TAG=$(git describe --tags --abbrev=0)
            COMMITS=$(git log ${PREV_TAG}..HEAD --pretty=format:'- %s')
          else
            PREV_TAG=""
            COMMITS=$(git log --pretty=format:'- %s')
          fi
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$COMMITS"      >> $GITHUB_ENV
          echo "EOF"           >> $GITHUB_ENV

      - name: Create release branch
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b releases/${VERSION}
          git push origin releases/${VERSION}


      - name: Debug Yandex auth in CI
        run: |
          echo "=== USER & PATH ==="
          whoami
          echo $PATH

          echo
          echo "=== yc info ==="
          which yc || echo "→ yc not in PATH"
          yc --version || echo "→ yc --version failed"

          echo
          echo "=== Attempt to get IAM token ==="
          TOKEN=$(yc iam create-token 2>&1) && echo "Token prefix: ${TOKEN:0:10}…" || echo "yc iam create-token failed: $TOKEN"

          echo
          echo "=== Docker config.json ==="
          cat ~/.docker/config.json || echo "no docker config"

          echo
          echo "=== Credential helper test ==="
          printf "https://cr.yandex" | docker-credential-yc get \
            && echo "credential-yc get → OK" \
            || echo "credential-yc get → FAILED"

          echo
          echo "=== env vars ==="
          echo "REGISTRY_HOST=$REGISTRY_HOST"
          echo "REGISTRY_ID=$REGISTRY_ID"

      

      - name: Build & Push Docker images
        run: |
            HOST=${REGISTRY_HOST}
            ID=${REGISTRY_ID}
            IMG=${HOST}/${ID}/app:${VERSION}
            IMG_L=${HOST}/${ID}/app:${VERSION}_latest

            # Тест, что helper работает:
            printf "https://${HOST}" | docker-credential-yc get

            docker build -t "$IMG" .
            docker tag   "$IMG" "$IMG_L"
            docker push  "$IMG"
            docker push  "$IMG_L"
      

      - name: Create git tag
        run: |
          git tag -a "${VERSION}" -m "Release ${VERSION}"
          git push origin "${VERSION}"

      - name: Update CHANGELOG.md
        run: |
          DATE=$(date -u +"%Y-%m-%d")
          { echo "## ${VERSION} - ${DATE}"; echo ""; echo "${COMMITS}"; echo ""; cat CHANGELOG.md; } \
            > CHANGELOG.tmp
          mv CHANGELOG.tmp CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG for release ${VERSION}"
          git push origin releases/${VERSION}

      - name: Create Release Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = process.env.VERSION;
            const date    = new Date().toISOString().split('T')[0];
            const author  = context.actor;
            const prev    = process.env.PREV_TAG;
            const commits = process.env.COMMITS;
            const image   = `cr.yandex/${process.env.REGISTRY_ID}/app:${version}`;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              title: `Release ${version} deployed`,
              body: `**Date:** ${date}
              **Author:** @${author}
              **Version:** ${version}
  
              **Commits since ${prev || 'start'}:**
              ${commits}
  
              **Docker image:** ${image}`
              });
